# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'vs2017-win2016'

  # strategy:
  #   maxParallel: 0
  #   matrix:
  #     # debug:
  #     #   _buildConfiguration: 'debug'
  #     release:
  #       _buildConfiguration: 'release'


steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'dmpe-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'dmpe_MeetupToRTM'
      cliProjectName: 'MeetupToRTM'
      cliProjectVersion: '1.3'
      cliSources: $(Build.SourcesDirectory)
      extraProperties: 'sonar.cs.vstest.reportsPaths=..\TestResults\*.trx'

  - task: NuGetToolInstaller@1

  - checkout: self
    submodules: true
    displayName: Download submodules

  - task: NuGetCommand@2
    displayName: Restore nuget packages for RememberTheMilkApi.sln
    inputs: 
      command: 'restore'
      solution: $(Build.SourcesDirectory)\RememberTheMilkApi\RememberTheMilkApi.sln
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: Building RememberTheMilkApi solution, a submodule
    inputs:
      solution: '$(Build.SourcesDirectory)\RememberTheMilkApi\RememberTheMilkApi.sln'
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      maximumCpuCount: true
      msbuildArchitecture: 'x64'

  - task: CopyFiles@2
    displayName: 'Copy Files to RTM lib of the $(Build.SourcesDirectory) where MeetupToRTM.csproj loads it'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)\RememberTheMilkApi\RememberTheMilkApi\bin\$(buildConfiguration)\'
      Contents: 'RememberTheMilkApi.dll'
      TargetFolder: '$(Build.SourcesDirectory)\WpfApp3\'
      CleanTargetFolder: false
      OverWrite: true
    condition: succeededOrFailed()

  #- script: |
  #    dir $(Build.ArtifactStagingDirectory) /s
  #    dir $(Build.SourcesDirectory) /s

  - task: NuGetCommand@2
    displayName: Restore nuget MeetupToRTM.csproj
    inputs: 
      command: 'restore'
      solution: $(Build.SourcesDirectory)\MeetupToRTM.sln
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: Build MeetupToRTM.csproj, creating exe file
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VisualStudioTestPlatformInstaller@1
    displayName: Prepare to build UnitTesting.csproj
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'latestStable'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*test*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      codeCoverageEnabled: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
      failTaskOnFailedTests: true
      platform: '$(buildPlatform)'
      buildConfiguration: '$(buildConfiguration)'

  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
  - task: ArchiveFiles@2
    displayName: 'Upload final exe and related files from zip archive to GitHub'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)\WpfApp3\bin'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      verbose: true

  - task: GitHubRelease@0
    displayName: 'GitHub release draft'
    inputs:
      gitHubConnection: 'dmpe'
      repositoryName: 'dmpe/MeetupToRTM'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: '$(Build.BuildNumber)'
      title: 'New Release: v.$(Build.BuildId)'
      assets: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      compareWith: 'lastRelease'
    continueOnError: true



