# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@0

- checkout: self
  submodules: true
  displayName: Download submodules

- task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'SonarQube Cloud io'
    projectKey: 'dmpe_MeetupToRTM'
    projectName: MeetupToRTM
    extraProperties: |
     sonar.organization=dmpe-github
     sonar.branch.name=master
  continueOnError: true
  condition: succeededOrFailed()

- task: NugetRestore@1
  displayName: Restore nuget packages for RememberTheMilkApi.sln
  inputs: 
    command: restore
    solution: $(Build.SourcesDirectory)\RememberTheMilkApi\RememberTheMilkApi.sln

- task: VSBuild@1
  displayName: Building RememberTheMilkApi solution
  inputs:
    solution: $(Build.SourcesDirectory)\RememberTheMilkApi\RememberTheMilkApi.sln
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourcesDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\RememberTheMilkApi\RememberTheMilkApi'
    Contents: '**\bin\$(BuildConfiguration)\*.dll'
    TargetFolder: '$(Build.SourcesDirectory)\WpfApp3\packages\'
    CleanTargetFolder: true
    OverWrite: true
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy Files to: bin/debug'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\RememberTheMilkApi\RememberTheMilkApi'
    Contents: '**\bin\$(BuildConfiguration)\*.dll'
    TargetFolder: '$(Build.SourcesDirectory)\bin\x86\Debug'
    CleanTargetFolder: true
    OverWrite: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: RememberTheMilkApi.dll
  condition: succeededOrFailed()

- script: |
    dir $(Build.ArtifactStagingDirectory) /s
    dir $(Build.SourcesDirectory)

- task: NugetRestore@2
  displayName: Restore nuget MeetupToRTM.csproj
  inputs: 
    command: restore
    solution: $(Build.SourcesDirectory)\MeetupToRTM.sln

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'

- task: GitHubRelease@0
  displayName: 'GitHub release draft'
  inputs:
    gitHubConnection: dmpe
    repositoryName: dmpe/MeetupToRTM
    title: '$(Parameters.title)'
    isPreRelease: true
  continueOnError: true
