# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube Cloud io'
    scannerMode: 'MSBuild'
    projectKey: 'dmpe_MeetupToRTM'
    projectName: 'MeetupToRTM'
    extraProperties: |
     sonar.organization=dmpe-github
     sonar.branch.name=master
  continueOnError: true
  condition: succeededOrFailed() 

- task: NuGetToolInstaller@1

- checkout: self
  submodules: true
  displayName: Download submodules

- task: NugetRestore@2
  displayName: Restore nuget packages for RememberTheMilkApi.sln
  inputs: 
    command: restore
    solution: $(Build.SourcesDirectory)\RememberTheMilkApi\RememberTheMilkApi.sln
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: Building RememberTheMilkApi solution, a submodule
  inputs:
    solution: '$(Build.SourcesDirectory)\RememberTheMilkApi\RememberTheMilkApi.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    maximumCpuCount: true
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'

- task: CopyFiles@2
  displayName: 'Copy Files to RTM lib of the $(Build.SourcesDirectory) where MeetupToRTM.csproj loads it'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\RememberTheMilkApi\RememberTheMilkApi\bin\Release\'
    Contents: 'RememberTheMilkApi.dll'
    TargetFolder: '$(Build.SourcesDirectory)\WpfApp3\'
    CleanTargetFolder: false
    OverWrite: true
  condition: succeededOrFailed()

#- script: |
#    dir $(Build.ArtifactStagingDirectory) /s
#    dir $(Build.SourcesDirectory) /s

- task: NugetRestore@2
  displayName: Restore nuget MeetupToRTM.csproj
  inputs: 
    command: restore
    solution: $(Build.SourcesDirectory)\MeetupToRTM.sln
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    maximumCpuCount: true
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
#    codeCoverageEnabled: true

- task: SonarQubeAnalyze@4

- task: GitHubRelease@0
  displayName: 'GitHub release draft'
  inputs:
    action: 'create'
    gitHubConnection: dmpe
    repositoryName: dmpe/MeetupToRTM
    title: "New Release"
    assets: $(Build.ArtifactStagingDirectory)/* 
    isPreRelease: true
  continueOnError: true
